name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/moon_cloud_fast_wind.png
  - assets/images/moon_cloud_mid_rain.png
  - assets/images/tornado.png
  - assets/images/sun_cloud_angled_rain.png
  - assets/images/sun_cloud_mid_rain.png
  - assets/vectors/rectangle_11_x2.svg
  - assets/vectors/rectangle_15_x2.svg
  - assets/vectors/rectangle_16_x2.svg
  - assets/vectors/rectangle_12_x2.svg
  - assets/vectors/rectangle_17_x2.svg
  - assets/vectors/rectangle_13_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/icon_mobile_signal_1_x2.svg
  - assets/vectors/ellipse_818_x2.svg
  - assets/vectors/icon_magnifyingglass_2_x2.svg
  - assets/vectors/battery_x2.svg

